spring:
  application:
    name: auth-demo  h2:    console:      enabled: true  jpa:    show-sql: true
server:  port: 8081
management:  endpoints:    web:      exposure:        include:        - "*"
logging:  level:
    ROOT: DEBUG
      
      
        